/* Copied from Code games/brain-brawl/questions.js by scripts/sync-games.sh. Edit the original, then run npm run sync-games. */
(function () {
var module = { exports: {} }, exports = module.exports;
var require = function (m) {
  if (m !== 'crypto') throw new Error('No browser version of ' + m);
  return {
    // a fair random whole number in [min, max), like Node's crypto.randomInt
    randomInt: function (min, max) {
      if (max === undefined) { max = min; min = 0; }
      var range = max - min, limit = Math.floor(4294967296 / range) * range, buf = new Uint32Array(1), x;
      do { window.crypto.getRandomValues(buf); x = buf[0]; } while (x >= limit);
      return min + (x % range);
    }
  };
};
// Brain Brawl's built-in questions. The game pulls fresh trivia from Open Trivia DB when the internet is up;
// these are the backup (and the only source for "Most likely to" prompts).
'use strict';

// [category, difficulty, question, correct answer, [three wrong answers]]
const MC = [
  ['Geography', 'easy', 'What is the capital of Australia?', 'Canberra', ['Sydney', 'Melbourne', 'Perth']],
  ['Geography', 'easy', 'Which is the longest river in South America?', 'Amazon', ['Paraná', 'Orinoco', 'Magdalena']],
  ['Geography', 'easy', 'What is the smallest country in the world by area?', 'Vatican City', ['Monaco', 'San Marino', 'Liechtenstein']],
  ['Geography', 'medium', 'Which country has the most natural lakes?', 'Canada', ['Finland', 'Russia', 'United States']],
  ['Geography', 'easy', 'What is the capital of Canada?', 'Ottawa', ['Toronto', 'Vancouver', 'Montreal']],
  ['Geography', 'medium', 'Mount Kilimanjaro is in which country?', 'Tanzania', ['Kenya', 'Uganda', 'Ethiopia']],
  ['Geography', 'easy', 'Which is the largest ocean on Earth?', 'Pacific', ['Atlantic', 'Indian', 'Arctic']],
  ['Geography', 'easy', 'What is the largest hot desert in the world?', 'Sahara', ['Arabian', 'Gobi', 'Kalahari']],
  ['Geography', 'easy', 'The city of Marrakesh is in which country?', 'Morocco', ['Egypt', 'Tunisia', 'Algeria']],
  ['Geography', 'medium', 'Which U.S. state has the longest coastline?', 'Alaska', ['Florida', 'California', 'Hawaii']],
  ['Geography', 'medium', 'What is the capital of New Zealand?', 'Wellington', ['Auckland', 'Christchurch', 'Queenstown']],
  ['Geography', 'hard', 'Which river flows through Baghdad?', 'Tigris', ['Euphrates', 'Jordan', 'Nile']],
  ['Geography', 'medium', 'Which African country has the largest population?', 'Nigeria', ['Ethiopia', 'Egypt', 'South Africa']],
  ['Geography', 'medium', 'The Strait of Gibraltar separates Spain from which country?', 'Morocco', ['Algeria', 'Portugal', 'Tunisia']],
  ['Geography', 'easy', 'In which city is the Colosseum?', 'Rome', ['Athens', 'Naples', 'Istanbul']],
  ['Geography', 'easy', 'What is the tallest mountain in the world above sea level?', 'Mount Everest', ['K2', 'Kangchenjunga', 'Mount Kilimanjaro']],
  ['Science & Nature', 'easy', 'What is the chemical symbol for gold?', 'Au', ['Ag', 'Gd', 'Go']],
  ['Science & Nature', 'easy', 'Which planet is known as the Red Planet?', 'Mars', ['Jupiter', 'Venus', 'Mercury']],
  ['Science & Nature', 'easy', 'Which gas do plants take in from the air for photosynthesis?', 'Carbon dioxide', ['Oxygen', 'Nitrogen', 'Hydrogen']],
  ['Science & Nature', 'medium', 'How many bones are in the adult human body?', '206', ['186', '212', '256']],
  ['Science & Nature', 'easy', 'What is the largest planet in our solar system?', 'Jupiter', ['Saturn', 'Neptune', 'Uranus']],
  ['Science & Nature', 'easy', 'Which part of the cell is known as its powerhouse?', 'Mitochondria', ['Nucleus', 'Ribosome', 'Golgi apparatus']],
  ['Science & Nature', 'medium', "What is the most abundant gas in Earth's atmosphere?", 'Nitrogen', ['Oxygen', 'Carbon dioxide', 'Argon']],
  ['Science & Nature', 'easy', 'At sea level, water boils at what temperature in Fahrenheit?', '212°F', ['200°F', '180°F', '100°F']],
  ['Science & Nature', 'easy', 'Which element has the atomic number 1?', 'Hydrogen', ['Helium', 'Oxygen', 'Carbon']],
  ['Science & Nature', 'medium', 'Roughly how fast does light travel, in kilometers per second?', '300,000', ['30,000', '3,000,000', '150,000']],
  ['Science & Nature', 'medium', 'Which blood type is known as the universal donor?', 'O negative', ['AB positive', 'A negative', 'O positive']],
  ['Science & Nature', 'medium', 'What is the closest star to Earth?', 'The Sun', ['Proxima Centauri', 'Sirius', 'Alpha Centauri A']],
  ['Science & Nature', 'easy', 'What is the largest organ of the human body?', 'Skin', ['Liver', 'Brain', 'Lungs']],
  ['Science & Nature', 'medium', 'How many hearts does an octopus have?', '3', ['1', '2', '8']],
  ['Science & Nature', 'easy', 'What is the hardest natural substance?', 'Diamond', ['Quartz', 'Titanium', 'Granite']],
  ['Science & Nature', 'easy', "What is the name of Jupiter's giant, long-lasting storm?", 'The Great Red Spot', ['The Great Dark Spot', 'The Eye', 'The Red Cyclone']],
  ['Science & Nature', 'hard', 'Which planet has the most known moons?', 'Saturn', ['Jupiter', 'Uranus', 'Neptune']],
  ['Animals', 'easy', 'What is the fastest land animal?', 'Cheetah', ['Pronghorn', 'Lion', 'Greyhound']],
  ['Animals', 'medium', 'What is a group of crows called?', 'A murder', ['A flock', 'A parliament', 'A gaggle']],
  ['Animals', 'easy', 'Which mammal can truly fly?', 'Bat', ['Flying squirrel', 'Sugar glider', 'Colugo']],
  ['Animals', 'medium', 'What is the largest animal known to have ever lived?', 'Blue whale', ['Argentinosaurus', 'Megalodon', 'African elephant']],
  ['Animals', 'easy', 'How many legs does a spider have?', '8', ['6', '10', '12']],
  ['Animals', 'easy', 'What is a baby kangaroo called?', 'Joey', ['Cub', 'Kit', 'Calf']],
  ['Animals', 'medium', 'Which Australian bird can mimic chainsaws and car alarms?', 'Lyrebird', ['Kookaburra', 'Cockatoo', 'Emu']],
  ['Animals', 'easy', 'What do giant pandas mostly eat?', 'Bamboo', ['Eucalyptus', 'Berries', 'Fish']],
  ['Animals', 'medium', 'Which mammal has the longest pregnancy?', 'Elephant', ['Blue whale', 'Giraffe', 'Rhinoceros']],
  ['Animals', 'medium', 'A "flamboyance" is a group of which birds?', 'Flamingos', ['Peacocks', 'Parrots', 'Swans']],
  ['History', 'easy', 'In what year did the Titanic sink?', '1912', ['1905', '1915', '1920']],
  ['History', 'easy', 'Who was the first President of the United States?', 'George Washington', ['John Adams', 'Thomas Jefferson', 'Benjamin Franklin']],
  ['History', 'easy', 'In what year did humans first land on the Moon?', '1969', ['1965', '1972', '1959']],
  ['History', 'easy', 'Which civilization built Machu Picchu?', 'The Inca', ['The Maya', 'The Aztec', 'The Olmec']],
  ['History', 'medium', 'In what year did the Berlin Wall fall?', '1989', ['1991', '1985', '1979']],
  ['History', 'medium', 'Who was the first woman to win a Nobel Prize?', 'Marie Curie', ['Mother Teresa', 'Jane Addams', 'Rosalind Franklin']],
  ['History', 'easy', 'Genghis Khan founded which empire?', 'Mongol Empire', ['Ottoman Empire', 'Persian Empire', 'Byzantine Empire']],
  ['History', 'medium', 'What was the first artificial satellite, launched in 1957?', 'Sputnik 1', ['Explorer 1', 'Vostok 1', 'Telstar']],
  ['History', 'easy', 'Which country gave the Statue of Liberty to the United States?', 'France', ['England', 'Spain', 'Italy']],
  ['Art', 'easy', 'Who painted the Mona Lisa?', 'Leonardo da Vinci', ['Michelangelo', 'Raphael', 'Donatello']],
  ['Entertainment: Film', 'easy', 'Which movie features the line "I\'ll be back"?', 'The Terminator', ['Die Hard', 'RoboCop', 'Predator']],
  ['Entertainment: Film', 'easy', 'In "The Lion King", what is the name of Simba\'s father?', 'Mufasa', ['Scar', 'Rafiki', 'Zazu']],
  ['Entertainment: Film', 'easy', 'Which animated movie features the song "Let It Go"?', 'Frozen', ['Tangled', 'Moana', 'Encanto']],
  ['Entertainment: Television', 'easy', 'What is the coffee shop called in the TV show "Friends"?', 'Central Perk', ["Java Joe's", 'The Grind', "Monk's Café"]],
  ['Entertainment: Film', 'easy', 'Who directed "Jurassic Park" (1993)?', 'Steven Spielberg', ['James Cameron', 'George Lucas', 'Ridley Scott']],
  ['Entertainment: Film', 'easy', 'In "Star Wars", what is the name of Han Solo\'s ship?', 'Millennium Falcon', ['Star Destroyer', 'X-Wing', 'Slave I']],
  ['Entertainment: Books', 'easy', 'Which school of witchcraft and wizardry does Harry Potter attend?', 'Hogwarts', ['Durmstrang', 'Beauxbatons', 'Ilvermorny']],
  ['Entertainment: Film', 'easy', 'Which color pill does Neo take in "The Matrix"?', 'Red', ['Blue', 'Green', 'White']],
  ['Entertainment: Film', 'easy', 'In "Toy Story", what is the name of the boy who owns Woody?', 'Andy', ['Sid', 'Bonnie', 'Danny']],
  ['Entertainment: Television', 'easy', 'Which TV series is set in the fictional town of Hawkins, Indiana?', 'Stranger Things', ['Riverdale', 'Twin Peaks', 'Gravity Falls']],
  ['Entertainment: Music', 'easy', 'Which band recorded the album "Abbey Road"?', 'The Beatles', ['The Rolling Stones', 'Pink Floyd', 'Led Zeppelin']],
  ['Entertainment: Music', 'easy', 'How many strings does a standard guitar have?', '6', ['4', '5', '7']],
  ['Entertainment: Music', 'easy', 'Who is known as the "King of Pop"?', 'Michael Jackson', ['Elvis Presley', 'Prince', 'Justin Timberlake']],
  ['Entertainment: Music', 'easy', 'Which singer released the album "1989"?', 'Taylor Swift', ['Adele', 'Katy Perry', 'Lady Gaga']],
  ['Entertainment: Music', 'easy', 'Which instrument did Louis Armstrong famously play?', 'Trumpet', ['Saxophone', 'Trombone', 'Clarinet']],
  ['Entertainment: Music', 'easy', 'Which country did the band ABBA come from?', 'Sweden', ['Norway', 'Denmark', 'Finland']],
  ['Entertainment: Music', 'easy', 'Freddie Mercury was the lead singer of which band?', 'Queen', ['Aerosmith', 'Kiss', 'The Who']],
  ['Sports', 'easy', 'How many players does a soccer team have on the field at once?', '11', ['10', '9', '12']],
  ['Sports', 'easy', 'In which sport would you perform a slam dunk?', 'Basketball', ['Volleyball', 'Tennis', 'Handball']],
  ['Sports', 'easy', 'How many rings are on the Olympic flag?', '5', ['4', '6', '7']],
  ['Sports', 'easy', 'Which country has won the most FIFA World Cup titles?', 'Brazil', ['Germany', 'Italy', 'Argentina']],
  ['Sports', 'easy', 'In tennis, what is a score of zero called?', 'Love', ['Nil', 'Zero', 'Duck']],
  ['Sports', 'medium', 'How long is a marathon, to the nearest mile?', '26 miles', ['24 miles', '30 miles', '22 miles']],
  ['Sports', 'easy', 'In bowling, what do you call knocking down all ten pins with the first ball?', 'Strike', ['Spare', 'Turkey', 'Split']],
  ['Sports', 'medium', 'What is the highest possible score in a game of ten-pin bowling?', '300', ['250', '200', '350']],
  ['Sports', 'easy', 'Which sport uses the terms "birdie", "eagle" and "bogey"?', 'Golf', ['Badminton', 'Cricket', 'Archery']],
  ['General Knowledge', 'easy', 'What is the main ingredient in guacamole?', 'Avocado', ['Tomato', 'Pea', 'Lime']],
  ['General Knowledge', 'easy', 'Paella comes from which country?', 'Spain', ['Italy', 'Portugal', 'Mexico']],
  ['General Knowledge', 'medium', 'Which pasta is shaped like grains of rice?', 'Orzo', ['Farfalle', 'Penne', 'Fusilli']],
  ['General Knowledge', 'medium', 'Which nut is used to make marzipan?', 'Almond', ['Cashew', 'Hazelnut', 'Walnut']],
  ['General Knowledge', 'easy', 'What is sushi usually wrapped in?', 'Seaweed', ['Rice paper', 'Lettuce', 'Soy paper']],
  ['General Knowledge', 'medium', 'How many minutes are in a day?', '1,440', ['1,240', '1,600', '1,140']],
  ['General Knowledge', 'medium', 'Which language has the most native speakers?', 'Mandarin Chinese', ['English', 'Spanish', 'Hindi']],
  ['General Knowledge', 'easy', 'How many sides does a hexagon have?', '6', ['5', '7', '8']],
  ['General Knowledge', 'easy', 'How many continents are there?', '7', ['5', '6', '8']],
  ['General Knowledge', 'easy', 'What does "www" stand for in a web address?', 'World Wide Web', ['World Web Wide', 'Wide World Web', 'Web World Wide']],
  ['General Knowledge', 'easy', 'What is the currency of Japan?', 'Yen', ['Won', 'Yuan', 'Ringgit']],
  ['General Knowledge', 'easy', 'What is the square root of 144?', '12', ['14', '11', '16']],
  ['Entertainment: Video Games', 'easy', 'Which princess does Mario usually rescue?', 'Princess Peach', ['Princess Zelda', 'Princess Daisy', 'Princess Rosalina']],
  ['Entertainment: Video Games', 'easy', 'In Minecraft, which block do you need to build a Nether portal?', 'Obsidian', ['Netherrack', 'Diamond', 'Bedrock']],
  ['Entertainment: Video Games', 'easy', 'Which company created the PlayStation?', 'Sony', ['Nintendo', 'Microsoft', 'Sega']],
  ['Entertainment: Video Games', 'easy', 'What color is Pac-Man?', 'Yellow', ['Red', 'Blue', 'Green']],
];

// [statement, true/false]
const TF = [
  ['The Great Wall of China is visible from the Moon with the naked eye.', false],
  ['Botanically, bananas are berries.', true],
  ['Botanically, strawberries are berries.', false],
  ['Octopuses have blue blood.', true],
  ['A group of owls is called a parliament.', true],
  ['The Eiffel Tower is slightly taller in summer than in winter.', true],
  ['Goldfish only have a three-second memory.', false],
  ['Venus is the hottest planet in our solar system.', true],
  ['Sharks are mammals.', false],
  ['Sealed honey can stay edible for thousands of years.', true],
  ['Sound travels faster through water than through air.', true],
  ['Botanically, a tomato is a fruit.', true],
  ['A day on Venus is longer than a year on Venus.', true],
  ['Albert Einstein won his Nobel Prize for the theory of relativity.', false],
  ['Penguins live at the North Pole.', false],
  ['The unicorn is the national animal of Scotland.', true],
  ['Napoleon was unusually short for his time, around five feet tall.', false],
  ['Lightning never strikes the same place twice.', false],
  ['Humans only use 10% of their brains.', false],
  ['A group of flamingos is called a flamboyance.', true],
  ['The Pacific is the smallest ocean on Earth.', false],
  ['Mount Everest is the tallest mountain on Earth when measured from base to peak.', false],
];

// Fibber prompts: weird-but-true facts. [prompt with ____, the truth, [three backup lies]]
const FIB = [
  ['The national animal of Scotland is the ____.', 'unicorn', ['griffin', 'red stag', 'golden eagle']],
  ['A group of flamingos is called a ____.', 'flamboyance', ['fiesta', 'blush', 'parade']],
  ['The first product ever scanned with a barcode at a checkout, in 1974, was a pack of ____.', 'chewing gum', ['cigarettes', 'bananas', 'coffee']],
  ["Before it was called Google, the search engine's working name was ____.", 'BackRub', ['Googol', 'Searchie', 'PageFind']],
  ["The dot over a lowercase i or j is called a ____.", 'tittle', ['jot', 'speck', 'pip']],
  ['A group of owls is called a ____.', 'parliament', ['senate', 'wisdom', 'hoot']],
  ['Wombats are famous for pooping ____.', 'cubes', ['stars', 'spirals', 'pyramids']],
  ['In Switzerland it is illegal to own just one ____, because it would get lonely.', 'guinea pig', ['goldfish', 'parrot', 'rabbit']],
  ['Bubble wrap was first invented to be sold as ____.', 'wallpaper', ['insulation', 'a pool cover', 'a toy']],
  ['Fredric Baur, who designed the Pringles can, had some of his ashes buried in a ____.', 'Pringles can', ['coffee tin', 'lunch box', 'bowling ball']],
  ["The world's first webcam was pointed at a ____ at Cambridge University.", 'coffee pot', ['fish tank', 'parking lot', 'bird feeder']],
  ['Honey bees can learn to recognize human ____.', 'faces', ['voices', 'names', 'smells']],
  ['The shortest war in history, between Britain and Zanzibar in 1896, lasted about ____.', '38 minutes', ['3 days', '2 hours', '11 minutes']],
  ['Cleopatra lived closer in time to the Moon landing than to the building of the ____.', 'Great Pyramid', ['Parthenon', 'Colosseum', 'Great Wall']],
  ['Sea otters hold ____ while they sleep so they don\'t drift apart.', 'hands', ['seaweed', 'rocks', 'tails']],
  ['A cross between a cow and a bison is called a ____.', 'beefalo', ['cowson', 'bisow', 'moofalo']],
  ["Monopoly is based on an earlier game called The ____ Game.", "Landlord's", ["Banker's", 'Property', 'Tycoon']],
  ['Nintendo was founded in 1889 as a company that made ____.', 'playing cards', ['kites', 'rice cookers', 'bicycles']],
  ['Ancient Romans used ____ as a tooth whitener.', 'urine', ['milk', 'vinegar', 'sand']],
  ['The Eiffel Tower was originally meant to stand for only ____ years.', '20', ['5', '50', '100']],
  ['Hollywood reuses a famous sound effect called the Wilhelm ____ in hundreds of movies.', 'scream', ['yell', 'sneeze', 'laugh']],
  ["An ostrich's eye is bigger than its ____.", 'brain', ['heart', 'stomach', 'beak']],
  ['When Ed Headrick, who designed the modern Frisbee, died, his ashes were molded into ____.', 'frisbees', ['a statue', 'a trophy', 'a kite']],
  ['The Hawaiian alphabet has only ____ letters.', '13', ['17', '20', '9']],
  ['Oxford University is older than the ____ Empire.', 'Aztec', ['Byzantine', 'Persian', 'Egyptian']],
  ['Peanuts are not really nuts. They are ____.', 'legumes', ['tubers', 'grasses', 'fungi']],
  ['Before toilet paper caught on, many Americans used pages from the ____ catalog.', 'Sears', ['IKEA', "Macy's", 'Walmart']],
  ['Scientists at the University of Richmond taught ____ to drive tiny cars for food.', 'rats', ['pigeons', 'hamsters', 'crows']],
  ["A shrimp's heart is located in its ____.", 'head', ['tail', 'back', 'legs']],
  ["Norway's King's Guard knighted a ____ named Sir Nils Olav.", 'penguin', ['moose', 'reindeer', 'horse']],
  ['The bird in the old Twitter logo had an official name: ____.', 'Larry', ['Tweety', 'Birdie', 'Jack']],
  ['Carrots were mostly ____ before the Dutch made orange ones popular.', 'purple', ['blue', 'green', 'pink']],
  ['Sherlock Holmes author Arthur Conan Doyle was trained as a ____.', 'doctor', ['lawyer', 'detective', 'baker']],
  ['The very first item ever sold on eBay was a broken ____.', 'laser pointer', ['toaster', 'Game Boy', 'lamp']],
  ['A pineapple plant takes about ____ years to grow a pineapple.', '2', ['5', '7', '10']],
  ['A group of porcupines is called a ____.', 'prickle', ['spike', 'thorn', 'needle']],
  ["In \"The Wizard of Oz\", Toto the dog was paid more per week than many of the actors who played the ____.", 'Munchkins', ['flying monkeys', 'Winkie guards', 'Emerald City guards']],
  ['The average cloud weighs about as much as 100 ____.', 'elephants', ['cars', 'houses', 'blue whales']],
  ['Octopuses have ____ hearts.', 'three', ['two', 'four', 'eight']],
  ['The inventor of the microwave oven discovered it when a ____ melted in his pocket.', 'chocolate bar', ['crayon', 'candle', 'marshmallow']],
];

// "Who is most likely to ___?"
const LIKELY = [
  'become famous', 'survive a zombie apocalypse', 'get lost in their own neighborhood', 'laugh at the worst possible moment',
  'eat something off the floor', 'win a reality TV show', 'talk their way out of a speeding ticket', 'forget their own birthday',
  'adopt ten cats', 'go viral online', "cry during a kids' movie", 'start a band', 'become a millionaire', 'text the wrong person',
  'fall asleep at a party', 'become president', 'get a tattoo on a dare', 'spend all their money on snacks', 'be late to their own wedding',
  'befriend a wild animal', 'sing karaoke without being asked', 'trip over absolutely nothing', 'binge a whole series in one day',
  'move to another country on a whim', 'secretly be a spy', 'buy something useless at 3am', 'eat the last slice without asking',
  'know every word to a cheesy song', 'survive on a desert island', 'accidentally set off a fire alarm', 'become a famous chef',
  'fall for an obvious prank', 'show up in pajamas', 'talk to their plants', 'have a secret talent', 'become a pro gamer',
  'lose their phone while holding it', 'go skydiving', 'start a conspiracy theory', 'write a bestselling book', 'end up on a game show',
  'win the lottery and lose the ticket', 'laugh at their own jokes', 'become a meme', 'fall asleep during a movie they picked',
  'give the best advice', 'plan an epic surprise party', 'wear socks with sandals', 'get lost in IKEA', 'live to 100',
  'open a restaurant', 'break a world record', 'cheat at board games', 'leave a party first', 'be the last one to leave a party',
  'pet every dog they see', 'take 100 selfies in a day', 'forget where they parked', 'invent something genius',
  'get a hole-in-one on their first try', 'accidentally join a flash mob', 'run a marathon', 'have the messiest room',
  'burn water', 'still sleep with a stuffed animal', 'become an influencer', 'survive a horror movie', 'scream at a jump scare',
  'actually read the terms and conditions', 'be a morning person', 'stay up until sunrise', 'talk in their sleep', 'text back instantly',
  'leave people on read', 'bring snacks to everything', 'rescue a stranger\'s lost pet', 'get recognized on the street', 'travel to space',
  'get stuck in an elevator', 'become a pro athlete', 'eat dessert first', "forget someone's name right after hearing it",
  'have the loudest sneeze', 'own a pet snake', 'dance on a table', 'organize the group trip', 'fall for a fake prize scam',
  'become a DJ', 'make everyone laugh at a serious moment', 'write a love song', 'pick up a very strange hobby',
  'have the best laugh', 'argue with a GPS', 'cry at a wedding', 'win a hot-dog eating contest', 'become a stand-up comedian',
  'get banned from a buffet', 'name their car', 'start a business in their garage', 'become a YouTube star',
];

module.exports = { MC, TF, FIB, LIKELY };

window.BB_PACK = module.exports;
})();
